defaults: &defaults
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

production:
  database: logstew_production
  allow_read_secondary: true
  replica_set:
    - uri: http://md1.internal
    - uri: http://md2.internal
    - uri: http://md3.internal
    - uri: http://md4.internal

development:
  <<: *defaults
  database: logstew_development
  replica_set:
    - uri: http://localhost:27018
    - uri: http://localhost:27019

test:
  <<: *defaults
  host: localhost
  database: logstew_test

#set these environment variables on your prod server
#production:
  #<<: *defaults
  #host: localhost
  #database: logstew_production

# how i secure mongo?
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
